# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_optorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optorder',
            name='order_id',
            field=models.CharField(max_length=20),
        ),
    ]
