# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('server', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u4e3b\u673a')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7528\u6237')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5bc6\u7801')),
                ('database', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u5b9e\u4f8b')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='\u6570\u636e\u5e93\u7c7b\u578b')),
                ('app_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.AppSystem')),
            ],
        ),
    ]
