# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-18 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_taskresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskresult',
            old_name='sql_result',
            new_name='sql_data',
        ),
    ]
