# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('record_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=50)),
                ('sz_account', models.CharField(max_length=50, null=True)),
                ('sh_account', models.CharField(max_length=50, null=True)),
                ('bank_account', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Underwriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underwriter', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
