# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180825_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underwriter',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
