# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180825_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=50)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_type', models.CharField(max_length=50)),
                ('zg_start_date', models.DateField()),
                ('zg_end_date', models.DateField()),
                ('cl_start_date', models.DateField()),
                ('cl_end_date', models.DateField()),
                ('xj_start_date', models.DateField()),
                ('xj_end_date', models.DateField()),
                ('sg_start_date', models.DateField()),
                ('sg_end_date', models.DateField()),
                ('jk_start_date', models.DateField()),
                ('jk_end_date', models.DateField()),
                ('ss_date', models.DateField(blank=True, null=True)),
                ('current_status', models.IntegerField(default=0)),
                ('underwriter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Underwriter')),
            ],
        ),
    ]
