# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20180831_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
