# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=50)),
                ('stock_name', models.CharField(max_length=50)),
                ('step', models.IntegerField()),
                ('current_status', models.IntegerField()),
                ('start_date', models.DateField()),
                ('done_time', models.DateTimeField()),
                ('product_list', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock')),
            ],
        ),
    ]
