# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('chinese_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.IntegerField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=20)),
                ('english_name', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('network', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('host_user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('chinese_name', models.CharField(max_length=50)),
                ('program_path', models.CharField(max_length=128)),
                ('script_path', models.CharField(max_length=128)),
                ('app_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.AppSystem')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='module',
            field=models.ManyToManyField(to='cmdb.Module'),
        ),
    ]
