# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20181229_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSystem',
            fields=[
                ('os_id', models.IntegerField(primary_key=True, serialize=False)),
                ('os_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cmdb_os',
            },
        ),
    ]
