# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_osystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cmdb.OSystem'),
        ),
    ]
