# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20190128_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='app_id',
            field=models.CharField(max_length=256),
        ),
    ]
