# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20190128_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='script_path',
        ),
        migrations.AddField(
            model_name='module',
            name='kwargs',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
