# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, unique=True)),
                ('chinese_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.IntegerField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=20)),
                ('english_name', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('network', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20, unique=True)),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('host_user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, unique=True)),
                ('chinese_name', models.CharField(max_length=50)),
                ('app_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.AppSystem')),
            ],
        ),
        migrations.CreateModel(
            name='OSystem',
            fields=[
                ('os_id', models.IntegerField(primary_key=True, serialize=False)),
                ('os_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cmdb_os',
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_code', models.CharField(max_length=5)),
                ('user_name', models.CharField(max_length=50)),
                ('app_id', models.CharField(max_length=256)),
                ('app_name', models.TextField()),
            ],
            options={
                'db_table': 'cmdb_app_user',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='module',
            field=models.ManyToManyField(to='cmdb.Module'),
        ),
        migrations.AddField(
            model_name='host',
            name='os_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cmdb.OSystem'),
        ),
    ]
