# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_module_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='kwargs',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
