# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20190323_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='program_path',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
