# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 06:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('keyword', models.CharField(max_length=128)),
                ('content', ckeditor.fields.RichTextField()),
                ('app_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.AppSystem')),
            ],
        ),
    ]
