# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0002_auto_20181229_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=16, unique=True)),
                ('type', models.IntegerField()),
                ('deploy_args', models.CharField(max_length=128, null=True)),
                ('creator', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateTimeField()),
                ('app_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.AppSystem')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.Module')),
            ],
        ),
    ]
