# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-10 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=16, unique=True)),
                ('type', models.IntegerField()),
                ('deploy_args', models.CharField(max_length=128, null=True)),
                ('create_time', models.DateTimeField()),
                ('remark', models.CharField(max_length=256, null=True)),
                ('update_time', models.DateTimeField()),
                ('current_env', models.IntegerField(default=0)),
                ('env_1', models.IntegerField(default=0)),
                ('env_2', models.IntegerField(default=0)),
                ('env_3', models.IntegerField(default=0)),
                ('env_4', models.IntegerField(default=0)),
                ('env_5', models.IntegerField(default=0)),
                ('app_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.AppSystem')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.Module')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=16)),
                ('host_ip', models.CharField(max_length=20)),
                ('module_name', models.CharField(max_length=50)),
                ('deploy_status', models.IntegerField()),
                ('deploy_time', models.DateTimeField()),
                ('deploy_log', models.TextField(default=' ')),
            ],
            options={
                'db_table': 'deploy_order_host',
            },
        ),
    ]
