# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-31 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0002_auto_20181229_1324'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=16, unique=True)),
                ('type', models.IntegerField()),
                ('deploy_args', models.CharField(max_length=128, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('env_1', models.IntegerField(default=0)),
                ('env_2', models.IntegerField(default=0)),
                ('env_3', models.IntegerField(default=0)),
                ('env_4', models.IntegerField(default=0)),
                ('env_5', models.IntegerField(default=0)),
                ('app_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.AppSystem')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.Module')),
            ],
        ),
    ]
