# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_order_current_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=16)),
                ('host_ip', models.CharField(max_length=20)),
                ('deploy_status', models.IntegerField()),
                ('deploy_time', models.DateTimeField()),
                ('deploy_log', models.TextField()),
            ],
            options={
                'db_table': 'deploy_order_host',
            },
        ),
    ]
