# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_orderhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhost',
            name='module_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderhost',
            name='deploy_log',
            field=models.TextField(default=' '),
        ),
    ]
